# ==============================================================================
#  Workflow: Pull Request Closed
# ==============================================================================
name: Pull Request Closed
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  # ============================================================================
  #  Job: squash-release
  # ============================================================================
  squash-release:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        node-version:
          - 14
        architecture:
          - x64
    env:
      TRACE: 1
      FORCE_COLOR: 1
      DOPPLER_ENVIRONMENT: ${{ secrets.DOPPLER_ENVIRONMENT }}
    steps:
    # ==========================================================================
    #  Step: Checkout source
    # ==========================================================================
    - name: Checkout source
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    
    # ==========================================================================
    #  Step: Setup Node js
    # ==========================================================================
    - name: Setup Node js
      uses: actions/setup-node@v2.1.5
      with:
        registry-url: https://npm.pkg.github.com
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}
    
    # ==========================================================================
    #  Step: Checkout private actions
    # ==========================================================================
    - name: Checkout private actions
      uses: rainspell/ga-checkout-private-actions@v1
      with:
        token: ${{ secrets.NPM_INSTALL_TOKEN }}
        actions: |
          rainspell/ga-setup-iris@v3
    
    # ==========================================================================
    #  Step: Setup iris
    # ==========================================================================
    - name: Setup iris
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_INSTALL_TOKEN }}
      uses: ./.github/actions/ga-setup-iris
      with:
        plugins: |
          @rainspell/iris-plugin-rainspell
    
    # ==========================================================================
    #  Step: Squash changes
    # ==========================================================================
    - name: Squash changes
      env:
        GH_API_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      run: iris rainspell release squash
    
  # ============================================================================
  #  Job: delete-previews
  # ============================================================================
  delete-previews:
    if: ${{ always() }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    needs: squash-release
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        node-version:
          - 14
        architecture:
          - x64
    env:
      TRACE: 1
      FORCE_COLOR: 1
      DOPPLER_ENVIRONMENT: ${{ secrets.DOPPLER_ENVIRONMENT }}
    steps:
    # ==========================================================================
    #  Step: Checkout source
    # ==========================================================================
    - name: Checkout source
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    
    # ==========================================================================
    #  Step: Setup Node js
    # ==========================================================================
    - name: Setup Node js
      uses: actions/setup-node@v2.1.5
      with:
        registry-url: https://npm.pkg.github.com
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}
    
    # ==========================================================================
    #  Step: Checkout private actions
    # ==========================================================================
    - name: Checkout private actions
      uses: rainspell/ga-checkout-private-actions@v1
      with:
        token: ${{ secrets.NPM_INSTALL_TOKEN }}
        actions: |
          rainspell/ga-setup-iris@v3
    
    # ==========================================================================
    #  Step: Setup iris
    # ==========================================================================
    - name: Setup iris
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_INSTALL_TOKEN }}
      uses: ./.github/actions/ga-setup-iris
      with:
        plugins: |
          @rainspell/iris-plugin-rainspell
    
    # ==========================================================================
    #  Step: Delete package previews
    # ==========================================================================
    - name: Delete package previews
      env:
        GH_API_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      run: iris rainspell package delete-preview